import * as vscode from 'vscode';
import * as path from 'path';

export interface EmailOptions {
    subject: string;
    recipientHint?: string;
    body: string;
    attachmentPath?: string;
    includeMetrics?: boolean;
}

export interface DocumentEmailOptions {
    documentType: 'LLD' | 'Review Report' | 'API Spec' | 'Spring Boot Project';
    projectName: string;
    source?: string;
    format?: string;
    completeness?: number;
    highlights: string[];
    filePath: string;
}

export class EmailService {
    /**
     * Opens user's email client with pre-filled content
     * Uses mailto: protocol - works with all email clients (Outlook, Gmail, etc.)
     * 
     * Note: mailto: protocol cannot automatically attach files for security reasons.
     * The file path is automatically copied to clipboard for easy manual attachment.
     */
    static async composeEmail(options: EmailOptions): Promise<void> {
        const config = vscode.workspace.getConfiguration('devex.email');
        const defaultRecipients = config.get<string[]>('defaultRecipients', []);
        const includeMetrics = config.get<boolean>('includeMetrics', true);
        const attachmentReminder = config.get<boolean>('attachmentReminder', true);
        
        // Build email subject
        const subject = encodeURIComponent(options.subject);
        
        // Build email body (note: remove attachment path from body since we'll handle it separately)
        let body = options.body;
        
        // Add metrics if enabled
        if (options.includeMetrics && includeMetrics) {
            body += '\n\n---\nGenerated by DevEx AI Assistant\n';
        }
        
        const encodedBody = encodeURIComponent(body);
        
        // Construct mailto: URL
        const mailto = `mailto:${defaultRecipients.join(',')}?subject=${subject}&body=${encodedBody}`;
        
        // If attachment exists, copy path to clipboard BEFORE opening email
        if (options.attachmentPath) {
            await vscode.env.clipboard.writeText(options.attachmentPath);
        }
        
        // Open in default email client
        await vscode.env.openExternal(vscode.Uri.parse(mailto));
        
        // Show prominent reminder with multiple options
        if (options.attachmentPath && attachmentReminder) {
            const fileName = path.basename(options.attachmentPath);
            
            // Give email client time to open, then show reminder
            setTimeout(async () => {
                const choice = await vscode.window.showWarningMessage(
                    `📎 ATTACHMENT REQUIRED\n\n` +
                    `File path copied to clipboard!\n` +
                    `File: ${fileName}\n\n` +
                    `To attach in Outlook:\n` +
                    `1. Click "Attach File"\n` +
                    `2. Click "Browse This PC"\n` +
                    `3. Paste path (Ctrl+V) in address bar\n` +
                    `4. Press Enter`,
                    { modal: false },
                    'Open Folder',
                    'Copy Path Again',
                    'Show Full Path'
                );
                
                if (choice === 'Copy Path Again') {
                    await vscode.env.clipboard.writeText(options.attachmentPath!);
                    vscode.window.showInformationMessage(`✅ Copied: ${fileName}`);
                } else if (choice === 'Open Folder') {
                    const folderPath = path.dirname(options.attachmentPath!);
                    await vscode.env.openExternal(vscode.Uri.file(folderPath));
                } else if (choice === 'Show Full Path') {
                    await vscode.window.showInformationMessage(
                        options.attachmentPath!,
                        { modal: true }
                    );
                    await vscode.env.clipboard.writeText(options.attachmentPath!);
                }
            }, 1500); // Wait 1.5 seconds for email to open
        }
    }
    
    /**
     * Generate standard email body for document sharing
     */
    static generateDocumentEmail(options: DocumentEmailOptions): EmailOptions {
        const { documentType, projectName, source, format, completeness, highlights, filePath } = options;
        
        const subject = `${documentType} Ready for Review: ${projectName}`;
        
        let body = `Hi Team,\n\n`;
        body += `I've completed the ${documentType} document for ${projectName}.\n\n`;
        
        body += `📋 Document Summary:\n`;
        if (source) {
            body += `- Source: ${source}\n`;
        }
        body += `- Generated: ${new Date().toLocaleDateString()}\n`;
        if (format) {
            body += `- Format: ${format}\n`;
        }
        if (completeness !== undefined) {
            body += `- Completeness: ${completeness}%\n`;
        }
        body += `\n`;
        
        body += `🎯 Key Highlights:\n`;
        highlights.forEach(h => body += `- ${h}\n`);
        body += `\n`;
        
        body += `Please review and provide feedback. The attached document includes all required sections and follows software engineering best practices.\n\n`;
        body += `Looking forward to your feedback!\n\n`;
        body += `Best regards`;
        
        return {
            subject,
            body,
            attachmentPath: filePath,
            includeMetrics: true
        };
    }
}
