import * as vscode from 'vscode';
const SwaggerParser = require('swagger-parser');
import { AIService } from '../services/aiService';
import { TelemetryService } from '../services/telemetryService';
import { logger } from '../utils/logger';

export async function parseOpenAPICommand(
    context: vscode.ExtensionContext,
    telemetryService: TelemetryService
): Promise<void> {
    const startTime = Date.now();

    try {
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            vscode.window.showErrorMessage('No active editor. Please open an OpenAPI specification file first.');
            return;
        }

        const document = editor.document;
        const content = document.getText();

        // Prompt for manual time estimate
        const manualTime = await promptManualTime();
        if (!manualTime) {
            return;
        }

        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Parsing OpenAPI Specification',
                cancellable: false
            },
            async (progress) => {
                progress.report({ increment: 0, message: 'Validating specification...' });

                // Validate OpenAPI spec
                try {
                    await SwaggerParser.validate(document.uri.fsPath);
                } catch (error: any) {
                    vscode.window.showErrorMessage(`Invalid OpenAPI specification: ${error.message}`);
                    return;
                }

                progress.report({ increment: 50, message: 'Analyzing with AI...' });

                const aiService = new AIService();
                const analysis = await aiService.parseOpenAPISpec(content);

                progress.report({ increment: 100, message: 'Analysis complete!' });

                // Show analysis in a new document
                const analysisDoc = await vscode.workspace.openTextDocument({
                    content: `# OpenAPI Specification Analysis\n\n${analysis}\n\n---\n\n*Generated by DevEx AI Assistant*`,
                    language: 'markdown'
                });

                await vscode.window.showTextDocument(analysisDoc, { viewColumn: vscode.ViewColumn.Beside });

                const actualTimeSeconds = (Date.now() - startTime) / 1000;
                await telemetryService.trackProductivityMetric('parse-openapi', manualTime, actualTimeSeconds);

                logger.info('OpenAPI specification parsed successfully');
            }
        );
    } catch (error: any) {
        logger.error('Failed to parse OpenAPI specification', error);
        vscode.window.showErrorMessage(`Failed to parse OpenAPI: ${error.message}`);
    }
}

async function promptManualTime(): Promise<number | undefined> {
    const options = [
        { label: '15 minutes', detail: '15' },
        { label: '30 minutes', detail: '30' },
        { label: '1 hour', detail: '60' }
    ];

    const selected = await vscode.window.showQuickPick(options, {
        placeHolder: 'How long would it take to analyze this OpenAPI spec manually?'
    });

    return selected ? parseInt(selected.detail) : undefined;
}
