import * as vscode from 'vscode';
import { AIService } from '../services/aiService';
import { TelemetryService } from '../services/telemetryService';
import { logger } from '../utils/logger';
import { extractDocxWithImages, analyzeImagesWithVision } from '../utils/imageAnalyzer';

export async function reviewLLDCommand(
    context: vscode.ExtensionContext,
    telemetryService: TelemetryService,
    fileUri?: vscode.Uri
): Promise<void> {
    const startTime = Date.now();

    try {
        let document: vscode.TextDocument | undefined;
        let filePath: string;

        // Try to get document from active editor or from provided URI
        if (fileUri) {
            // Called from context menu on a file in Explorer
            filePath = fileUri.fsPath;
            const fileExtension = filePath.substring(filePath.lastIndexOf('.'));
            
            // Check if file type is supported
            if (!['.md', '.txt', '.docx'].includes(fileExtension.toLowerCase())) {
                vscode.window.showWarningMessage('This command supports .md, .txt, and .docx files.');
                return;
            }

            // For .docx files, don't try to open as text document (they're binary)
            // For text files, open them
            if (fileExtension.toLowerCase() !== '.docx') {
                document = await vscode.workspace.openTextDocument(fileUri);
                await vscode.window.showTextDocument(document, { preview: false });
            }
        } else {
            // Called from command palette - need active editor (unless it's a .docx)
            const editor = vscode.window.activeTextEditor;
            if (!editor) {
                vscode.window.showErrorMessage('No active editor. Please open an LLD document first, or use the right-click menu for .docx files.');
                return;
            }
            document = editor.document;
            filePath = document.fileName;
            
            const fileExtension = filePath.substring(filePath.lastIndexOf('.'));
            
            // Check if file type is supported
            if (!['.md', '.txt', '.docx'].includes(fileExtension.toLowerCase())) {
                vscode.window.showWarningMessage('This command supports .md, .txt, and .docx files.');
                return;
            }
        }

        const fileExtension = filePath.substring(filePath.lastIndexOf('.'));

        // Prompt for focus area
        const focusArea = await promptFocusArea();
        if (!focusArea) {
            return;
        }

        // Prompt for manual time estimate
        const manualTime = await promptManualTime();
        if (!manualTime) {
            return;
        }

        let content: string;
        let imageAnalysis = '';

        // Extract content based on file type
        if (fileExtension.toLowerCase() === '.docx') {
            // For .docx files, extract text and images using mammoth
            try {
                const result = await extractDocxWithImages(filePath);
                content = result.content;
                
                // Analyze images if present
                if (result.images.length > 0) {
                    logger.info(`Found ${result.images.length} images, analyzing...`);
                    imageAnalysis = await analyzeImagesWithVision(result.images, 'architecture');
                }
            } catch (error: any) {
                throw new Error(`Failed to read .docx file: ${error.message}`);
            }
        } else {
            // For text-based files (.md, .txt), read directly
            content = document!.getText();
        }

        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Reviewing LLD as Principal Architect',
                cancellable: false
            },
            async (progress) => {
                progress.report({ increment: 0, message: 'Analyzing architecture with AI...' });

                const aiService = new AIService();
                
                // Combine content with image analysis if available
                const fullContent = imageAnalysis ? 
                    `${content}\n\n## Additional Information from Images/Diagrams:\n${imageAnalysis}` : 
                    content;
                
                const review = await aiService.reviewLLDAsArchitect(fullContent, focusArea);

                progress.report({ increment: 100, message: 'Architectural review complete!' });

                // Show review in a new document
                const reviewDoc = await vscode.workspace.openTextDocument({
                    content: `# Principal Architect Review\n\n**Focus Area:** ${focusArea}\n\n${review}\n\n---\n\n*Generated by DevEx AI Assistant*`,
                    language: 'markdown'
                });

                await vscode.window.showTextDocument(reviewDoc, { viewColumn: vscode.ViewColumn.Beside });

                const actualTimeSeconds = (Date.now() - startTime) / 1000;
                await telemetryService.trackProductivityMetric('review-lld', manualTime, actualTimeSeconds);

                logger.info('LLD reviewed successfully');
            }
        );
    } catch (error: any) {
        logger.error('Failed to review LLD', error);
        vscode.window.showErrorMessage(`Failed to review LLD: ${error.message}`);
    }
}

async function promptFocusArea(): Promise<string | undefined> {
    const options = [
        { label: 'Code Generation Readiness', detail: 'Check if LLD has complete details for production-ready code generation' },
        { label: 'Software Engineering Completeness', detail: 'Comprehensive: error handling, state, security, performance, ops' },
        { label: 'API Design Completeness', detail: 'Check if LLD has all details for OpenAPI/Code generation' },
        { label: 'Integration APIs', detail: 'Focus on integration layer and external system connections' },
        { label: 'Backend APIs (BFF/Domain)', detail: 'Focus on backend architecture and API design' },
        { label: 'Frontend Architecture', detail: 'Focus on frontend components and MFE architecture' },
        { label: 'Overall Architecture', detail: 'Review entire system architecture and design decisions' },
        { label: 'Custom', detail: 'Enter your own focus area' }
    ];

    const selected = await vscode.window.showQuickPick(options, {
        placeHolder: 'What should the architectural review focus on?',
        title: 'LLD Review Focus'
    });

    if (!selected) {
        return undefined;
    }

    if (selected.label === 'Custom') {
        return await vscode.window.showInputBox({
            prompt: 'Enter your focus area for the architectural review',
            placeHolder: 'e.g., Data modeling, Security, Performance optimization'
        });
    }

    return selected.label;
}

async function promptManualTime(): Promise<number | undefined> {
    const options = [
        { label: '30 minutes', detail: '30' },
        { label: '1 hour', detail: '60' },
        { label: '2 hours', detail: '120' }
    ];

    const selected = await vscode.window.showQuickPick(options, {
        placeHolder: 'How long would a principal architect take to review this LLD manually?'
    });

    return selected ? parseInt(selected.detail) : undefined;
}
