import * as vscode from 'vscode';
import { AIService } from '../services/aiService';
import { TelemetryService } from '../services/telemetryService';
import { logger } from '../utils/logger';
import { extractDocxWithImages, analyzeImagesWithVision } from '../utils/imageAnalyzer';

export async function summarizeLLDCommand(
    context: vscode.ExtensionContext,
    telemetryService: TelemetryService,
    fileUri?: vscode.Uri
): Promise<void> {
    const startTime = Date.now();

    try {
        let document: vscode.TextDocument | undefined;
        let filePath: string;

        // Try to get document from active editor or from provided URI
        if (fileUri) {
            // Called from context menu on a file in Explorer
            filePath = fileUri.fsPath;
            const fileExtension = filePath.substring(filePath.lastIndexOf('.'));
            
            // Check if file type is supported
            if (!['.md', '.txt', '.docx'].includes(fileExtension.toLowerCase())) {
                vscode.window.showWarningMessage('This command supports .md, .txt, and .docx files.');
                return;
            }

            // For .docx files, don't try to open as text document (they're binary)
            // For text files, open them
            if (fileExtension.toLowerCase() !== '.docx') {
                document = await vscode.workspace.openTextDocument(fileUri);
                await vscode.window.showTextDocument(document, { preview: false });
            }
        } else {
            // Called from command palette - need active editor (unless it's a .docx)
            const editor = vscode.window.activeTextEditor;
            if (!editor) {
                vscode.window.showErrorMessage('No active editor. Please open an LLD document first, or use the right-click menu for .docx files.');
                return;
            }
            document = editor.document;
            filePath = document.fileName;
            
            const fileExtension = filePath.substring(filePath.lastIndexOf('.'));
            
            // Check if file type is supported
            if (!['.md', '.txt', '.docx'].includes(fileExtension.toLowerCase())) {
                vscode.window.showWarningMessage('This command supports .md, .txt, and .docx files.');
                return;
            }
        }

        const fileExtension = filePath.substring(filePath.lastIndexOf('.'));

        // Prompt for manual time estimate
        const manualTime = await promptManualTime();
        if (!manualTime) {
            return;
        }

        let content: string;
        let imageAnalysis = '';

        // Extract content based on file type
        if (fileExtension.toLowerCase() === '.docx') {
            // For .docx files, extract text and images using mammoth
            try {
                const result = await extractDocxWithImages(filePath);
                content = result.content;
                
                // Analyze images if present
                if (result.images.length > 0) {
                    logger.info(`Found ${result.images.length} images, analyzing...`);
                    imageAnalysis = await analyzeImagesWithVision(result.images, 'general');
                }
            } catch (error: any) {
                throw new Error(`Failed to read .docx file: ${error.message}`);
            }
        } else {
            // For text-based files (.md, .txt), read directly
            content = document!.getText();
        }

        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Summarizing LLD Document',
                cancellable: false
            },
            async (progress) => {
                progress.report({ increment: 0, message: 'Analyzing document with AI...' });

                const aiService = new AIService();
                
                // Combine content with image analysis if available
                const fullContent = imageAnalysis ? 
                    `${content}\n\n## Additional Information from Images/Diagrams:\n${imageAnalysis}` : 
                    content;
                
                const summary = await aiService.summarizeLLD(fullContent);

                progress.report({ increment: 100, message: 'Summary generated!' });

                // Show summary in a new document
                const summaryDoc = await vscode.workspace.openTextDocument({
                    content: `# LLD Summary\n\n${summary}\n\n---\n\n*Generated by DevEx AI Assistant*`,
                    language: 'markdown'
                });

                await vscode.window.showTextDocument(summaryDoc, { viewColumn: vscode.ViewColumn.Beside });

                const actualTimeSeconds = (Date.now() - startTime) / 1000;
                await telemetryService.trackProductivityMetric('summarize-lld', manualTime, actualTimeSeconds);

                logger.info('LLD summarized successfully');
            }
        );
    } catch (error: any) {
        logger.error('Failed to summarize LLD', error);
        vscode.window.showErrorMessage(`Failed to summarize LLD: ${error.message}`);
    }
}

async function promptManualTime(): Promise<number | undefined> {
    const options = [
        { label: '15 minutes', detail: '15' },
        { label: '30 minutes', detail: '30' },
        { label: '1 hour', detail: '60' }
    ];

    const selected = await vscode.window.showQuickPick(options, {
        placeHolder: 'How long would it take to read and understand this LLD manually?'
    });

    return selected ? parseInt(selected.detail) : undefined;
}
