import * as vscode from 'vscode';
import { AIService } from '../services/aiService';
import { TelemetryService } from '../services/telemetryService';
import { logger } from '../utils/logger';

export async function summarizeLLDCommand(
    context: vscode.ExtensionContext,
    telemetryService: TelemetryService
): Promise<void> {
    const startTime = Date.now();

    try {
        const editor = vscode.window.activeTextEditor;
        if (!editor) {
            vscode.window.showErrorMessage('No active editor. Please open an LLD document first.');
            return;
        }

        const document = editor.document;
        if (!['.md', '.txt'].includes(document.fileName.substring(document.fileName.lastIndexOf('.')))) {
            vscode.window.showWarningMessage('This command works best with Markdown (.md) files.');
        }

        // Prompt for manual time estimate
        const manualTime = await promptManualTime();
        if (!manualTime) {
            return;
        }

        const content = document.getText();

        await vscode.window.withProgress(
            {
                location: vscode.ProgressLocation.Notification,
                title: 'Summarizing LLD Document',
                cancellable: false
            },
            async (progress) => {
                progress.report({ increment: 0, message: 'Analyzing document with AI...' });

                const aiService = new AIService();
                const summary = await aiService.summarizeLLD(content);

                progress.report({ increment: 100, message: 'Summary generated!' });

                // Show summary in a new document
                const summaryDoc = await vscode.workspace.openTextDocument({
                    content: `# LLD Summary\n\n${summary}\n\n---\n\n*Generated by DevEx AI Assistant*`,
                    language: 'markdown'
                });

                await vscode.window.showTextDocument(summaryDoc, { viewColumn: vscode.ViewColumn.Beside });

                const actualTimeSeconds = (Date.now() - startTime) / 1000;
                await telemetryService.trackProductivityMetric('summarize-lld', manualTime, actualTimeSeconds);

                logger.info('LLD summarized successfully');
            }
        );
    } catch (error: any) {
        logger.error('Failed to summarize LLD', error);
        vscode.window.showErrorMessage(`Failed to summarize LLD: ${error.message}`);
    }
}

async function promptManualTime(): Promise<number | undefined> {
    const options = [
        { label: '15 minutes', detail: '15' },
        { label: '30 minutes', detail: '30' },
        { label: '1 hour', detail: '60' }
    ];

    const selected = await vscode.window.showQuickPick(options, {
        placeHolder: 'How long would it take to read and understand this LLD manually?'
    });

    return selected ? parseInt(selected.detail) : undefined;
}
