#!/usr/bin/env python3
"""
KT Session Batch Transcriber
Generated by DevEx AI Assistant (Spec2PR extension)

Usage:
    python kt-transcribe-runner.py <config.json>

The config.json is written by the VS Code extension and auto-deleted after reading.
When all files are transcribed, a .kt-transcribe-complete.json is written to the
output folder. Run "DevEx: Structure KT Transcripts" in VS Code to generate AI notes.
"""

import json
import sys
import os
import subprocess
import urllib.request
import urllib.error
import datetime
import time


# ── Logging ───────────────────────────────────────────────────────────────────

def log(msg: str, log_file: str) -> None:
    ts = datetime.datetime.now().strftime('%H:%M:%S')
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with open(log_file, 'a', encoding='utf-8') as f:
        f.write(line + '\n')


# ── Download ──────────────────────────────────────────────────────────────────

def download_file(url: str, dest_path: str, token: str | None = None) -> None:
    os.makedirs(os.path.dirname(dest_path), exist_ok=True)
    req = urllib.request.Request(url)
    if token:
        req.add_header('Authorization', f'Bearer {token}')
    with urllib.request.urlopen(req, timeout=300) as response:
        total = int(response.headers.get('Content-Length', 0))
        downloaded = 0
        with open(dest_path, 'wb') as out:
            while True:
                chunk = response.read(1024 * 1024)  # 1 MB chunks
                if not chunk:
                    break
                out.write(chunk)
                downloaded += len(chunk)
                if total:
                    pct = int(downloaded * 100 / total)
                    print(f'\r    {pct}% ({downloaded // (1024*1024)} / {total // (1024*1024)} MB)   ', end='', flush=True)
                else:
                    print(f'\r    {downloaded // (1024*1024)} MB downloaded...', end='', flush=True)
    print()  # newline after progress


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python kt-transcribe-runner.py <config.json>")
        sys.exit(1)

    config_path = sys.argv[1]
    if not os.path.exists(config_path):
        print(f"ERROR: Config file not found: {config_path}")
        sys.exit(1)

    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    # Delete config immediately — it may contain auth tokens
    try:
        os.unlink(config_path)
    except Exception:
        pass

    output_dir  = config['outputDir']
    model       = config['model']
    python_cmd  = config['pythonCmd']
    files       = config['files']
    temp_dir    = os.path.join(os.environ.get('TEMP', '/tmp'), 'devex-kt-recordings')

    os.makedirs(output_dir, exist_ok=True)
    log_file = os.path.join(output_dir, 'transcription-log.txt')

    # ── Header ────────────────────────────────────────────────────────────────
    print("=" * 60)
    print("  KT Session Batch Transcriber — DevEx AI Assistant")
    print("=" * 60)
    log(f"Model   : {model}", log_file)
    log(f"Files   : {len(files)}", log_file)
    log(f"Output  : {output_dir}", log_file)
    log(f"Started : {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", log_file)
    log("", log_file)

    results = []

    for i, file_info in enumerate(files):
        name = file_info.get('name', f'recording_{i+1}')
        log(f"[{i+1}/{len(files)}] {name}", log_file)

        # ── Download if needed ────────────────────────────────────────────────
        local_path = file_info.get('localPath')

        if not local_path and file_info.get('downloadUrl'):
            dl_path = os.path.join(temp_dir, name)
            log(f"  Downloading...", log_file)
            try:
                download_file(
                    file_info['downloadUrl'],
                    dl_path,
                    token=file_info.get('downloadToken')
                )
                local_path = dl_path
                log(f"  Downloaded OK → {dl_path}", log_file)
            except Exception as e:
                log(f"  DOWNLOAD FAILED: {e}", log_file)
                results.append({'name': name, 'status': 'failed', 'error': str(e)})
                continue

        if not local_path or not os.path.exists(local_path):
            log(f"  ERROR: file not found: {local_path}", log_file)
            results.append({'name': name, 'status': 'failed', 'error': 'file not found'})
            continue

        # ── Transcribe ────────────────────────────────────────────────────────
        log(f"  Transcribing with Whisper ({model})...", log_file)
        start_t = time.time()

        whisper_proc = subprocess.run(
            [
                python_cmd, '-m', 'whisper',
                local_path,
                '--model', model,
                '--output_format', 'txt',
                '--output_dir', output_dir
            ]
        )

        elapsed = int(time.time() - start_t)
        mins, secs = divmod(elapsed, 60)

        if whisper_proc.returncode != 0:
            log(f"  WHISPER FAILED (exit code {whisper_proc.returncode})", log_file)
            results.append({'name': name, 'status': 'failed',
                           'error': f'whisper exit code {whisper_proc.returncode}'})
        else:
            base = os.path.splitext(name)[0]
            txt_path = os.path.join(output_dir, f'{base}.txt')
            log(f"  Transcribed in {mins}m {secs}s → {txt_path}", log_file)
            results.append({'name': name, 'status': 'done',
                           'transcript': txt_path, 'elapsedSec': elapsed})

        # ── Clean up temp download ────────────────────────────────────────────
        if file_info.get('downloadUrl') and local_path and os.path.exists(local_path):
            try:
                os.unlink(local_path)
            except Exception:
                pass

    # ── Summary ───────────────────────────────────────────────────────────────
    done  = [r for r in results if r['status'] == 'done']
    failed = [r for r in results if r['status'] == 'failed']

    log("", log_file)
    log("=" * 60, log_file)
    log(f"DONE: {len(done)}/{len(files)} transcribed successfully.", log_file)
    if failed:
        log(f"FAILED: {', '.join(r['name'] for r in failed)}", log_file)
    log("", log_file)
    log("Next step — generate AI structured notes:", log_file)
    log("  VS Code → Command Palette → DevEx: Structure KT Transcripts", log_file)
    log(f"  Select folder: {output_dir}", log_file)
    log("=" * 60, log_file)

    # ── Write completion marker ───────────────────────────────────────────────
    completion = {
        'completedAt': datetime.datetime.now().isoformat(),
        'outputDir': output_dir,
        'model': model,
        'results': results
    }
    marker_path = os.path.join(output_dir, '.kt-transcribe-complete.json')
    with open(marker_path, 'w', encoding='utf-8') as f:
        json.dump(completion, f, indent=2)

    print()
    print("Press Enter to close this window...")
    input()


if __name__ == '__main__':
    main()
